# Generated by Django 5.2.8 on 2025-12-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_comment_delete_logmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('group', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=250)),
                ('pricing', models.CharField(max_length=10)),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
