# Generated by Django 5.2.8 on 2025-12-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='pricing',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
