# Generated by Django 6.0 on 2025-12-15 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='username',
        ),
    ]
